using UnityEngine;
using System.Collections;

public enum N_Bind_Idx
{
    NONE = 0,

    MATCHCOUNT_BLOCKTYPE_START_IDX = 100,
    MATCHCOUNT_BLOCKTYPE1,
    MATCHCOUNT_BLOCKTYPE2,
    MATCHCOUNT_BLOCKTYPE3,
    MATCHCOUNT_BLOCKTYPE4,
    MATCHCOUNT_BLOCKTYPE5,
    MATCHCOUNT_BLOCKTYPE6,
    MATCHCOUNT_BLOCKTYPE7,
    MATCHCOUNT_BLOCKTYPE8,
    MATCHCOUNT_BLOCKTYPE9,
    MATCHCOUNT_BLOCKTYPE10,
    MATCHCOUNT_BLOCKTYPE11,
    MATCHCOUNT_BLOCKTYPE12,
    MATCHCOUNT_BLOCKTYPE13,
    MATCHCOUNT_BLOCKTYPE14,
    MATCHCOUNT_BLOCKTYPE15,
}

public enum F_Bind_Idx
{
    NONE = 0,

}

public enum S_Bind_Idx
{
    NONE = 0,
}

public enum B_Bind_Idx
{
    NONE = 0,

    EDIT_MODE = 100,

    BLOCK_ALL_READY = 10000,
}

public enum V2_Bind_Idx
{
    NONE = 0,

    POINTER_EDITOR_SELECTMODE_DRAG = 100,
    POINTER_EDITOR_SELECTMODE_BEGIN_DRAG,
    POINTER_EDITOR_SELECTMODE_END_DRAG,
}